# Day 3 Assignment
## Question 1

In [3]:
import numpy as np

a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question 2 

In [33]:
import numpy as np

li1=[]
li2=[]
print("Enter the elements of first array")
for i in range(5):
    li1.append(input())
print("\nEnter the elements of second array")
for i in range(5):
    li2.append(input())
arr1=np.array(li1)
arr2=np.array(li2)
arr3=np.concatenate((arr1, arr2))
print("\nArray after concatenate: ")
print(arr3)
arr3=np.sort(arr3)
print("\nArray after sorting: ")
print(arr3)

Enter the elements of first array
5
4
3
2
1

Enter the elements of second array
10
9
8
7
6

Array after concatenate: 
['5' '4' '3' '2' '1' '10' '9' '8' '7' '6']

Array after sorting: 
['1' '10' '2' '3' '4' '5' '6' '7' '8' '9']


## Question 3

In [37]:
import numpy as np

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


## Question 4 

We can convert 1D array to 2D array using replace() function in numpy. We can also use np.newaxis and np.expand_dims

### Using newaxis()

In [61]:
import numpy as np

arr = np.array([1, 2,3,4,5]) 
print(arr.shape) 
  
arr = np.expand_dims(arr, axis = 0) 
print(arr.shape) 

(5,)
(1, 5)


### Using expand_dims()

In [62]:
import numpy as np

arr = np.array([1,2,3,4,5]) 
print(arr.shape) 
  
new_arr = arr[np.newaxis]
print(new_arr.shape) 

(5,)
(1, 5)


## Question 5

### Using vstack()

In [2]:
import numpy as np

arr1 =[[1,2,3,4,5],
      [6,7,8,9,10]]

arr2 =[[11,12,13,14,15],
      [16,17,18,19,20]]
print(np.vstack((arr1,arr2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Using hstach()

In [3]:
print(np.hstack((arr1,arr2)))

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


## Question 6 

In [28]:
import numpy as np

arr = np.array([1,2,3,4,5,6,1,2,3,5,4,7,8,1])
unique, counts = np.unique(arr, return_counts=1)
for i in range(len(unique)):
    print("Element",unique[i],"occurs",counts[i],"times")


Element 1 occurs 3 times
Element 2 occurs 2 times
Element 3 occurs 2 times
Element 4 occurs 2 times
Element 5 occurs 2 times
Element 6 occurs 1 times
Element 7 occurs 1 times
Element 8 occurs 1 times
